### ISSUE TITLE
V 2.0 release launch checklist

### ISSUE THREAD

**Issue by abose** [brackets-cont/brackets#59]
Things to do to release brackets v 2.0 on launch day

## Complete code changes
- [x] Update about box with contributor names for latest release https://github.com/brackets-cont/brackets/pull/79
- [x] #86
- [x] #87
- [x] https://github.com/brackets-cont/brackets/issues/46
- [x] https://github.com/brackets-cont/brackets/issues/45
- [x] Install windows build and Verify build number of new brackets build greater than last brackets build. Build number can be found in the About box in the version number string `z.y.z-Build number`
- [x] Install mac build and verify build number

## Release checklist
- [x] Create release notes like this https://github.com/adobe/brackets/wiki/Release-Notes:-1.14 
- [x] Post pre-release builds with the release notes as content.
- [x] Put in a visible pre-release button on brackets.io  https://github.com/brackets-cont/brackets-cont.github.io/pull/14
### Do this after posting pre-release builds for 2 weeks
**Please note that any change we do to create a new installer should have a bump in minor version, Eg. 2.0.1 to 2.0.2 by updating the version number from the source and rebuilding installers again.** 
- [x] Take down the pre-release button. https://github.com/brackets-cont/brackets-cont.github.io/pull/16
- [x] Update download button to point to new release
### Do this After the release is live in the website for a week.
- [x] Send update notifications to existing users.
- [ ] Setup auto update links

**Comment by abose** [comment]
Autoupdate is not being rolled out for this release as:
1. The new installer is not MSI file and hence not compatible with auto-update infra in place currently
2. Not creating MSI as we have a scheduled end of JAN release that will have an MSI installer just for auto-updates.
3. We don't want to auto-update this release as the project transitioned to the community from Adobe and prefer an explicit update.
